name: Python CI

on:
  push:
    branch:
     -main


jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Verify Python
        uses: python --version

      - name: Run Application
        uses: python app.py  
